services:
  node_app:
    image: ghcr.io/medvesek/fastify-example:latest
    expose:
      - 80
    networks:
      - default
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastify_example.rule=Host(`fastify-example.ajmuht.eu`)"
      - "traefik.http.routers.fastify_example.entrypoints=websecure"
      - "traefik.http.routers.fastify_example.tls.certresolver=le"
      - "traefik.http.services.fastify_example.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
