services:
  node_app:
    image: ghcr.io/medvesek/fastify-example:latest
    networks:
      - default
      - traefik-net
    deploy:
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fastify_example.rule=Host(`fastify-example.ajmuht.eu`)"
        - "traefik.http.routers.fastify_example.tls.certresolver=le"
        - "traefik.http.services.fastify_example.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
