- name: Deploy
  hosts: all
  tasks:
    - name: ensures dir exists
      file:
        path: "~/docker/apps/fastify-example"
        state: directory

    - name: Copy docker compose
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: ~/docker/apps/fastify-example/docker-compose.yml

    - name: Run docker compose fastify example
      community.docker.docker_stack:
        state: present
        name: fastify-example
        compose:
          - /root/docker/apps/fastify-example
